Testing new integration test

diff --git a/project/3_CI_CD/Jenkinsfile b/project/3_CI_CD/Jenkinsfile
--- a/project/3_CI_CD/Jenkinsfile
+++ b/project/3_CI_CD/Jenkinsfile
@@ -139,33 +139,46 @@ pipeline {
 
             //     stage("Run tests") {
 
-                    agent any
+                    // agent any
+
+                    agent {
+                        docker {
+                            image 'in92/devops_omm_intest:v1.1'
+                            args '-w /pybox/model'
+                        }
+                     }
 
                     steps {
-
-                        script {
-
-                            docker.image('in92/devops_score_sidecar:v1.6').withRun('-p 9999:9999') { test ->
-                                docker.image('in92/devops_score_sidecar:v1.6').inside("-u 0 --entrypoint=/pybox/app/startServer.sh --link ${test.id}:test_score") {
-                                }
-
-                            docker.image('in92/devops_test_exec:v1.2').inside("--workdir=/home/test --link ${test.id}:test_score") {
-
-                                    env.TOKEN = sh(script:"curl -s test_score:9999/", returnStdout: true).trim()
-                                    sh(returnStdout: true, script: "if [ ${env.TOKEN} == 'pong' ]; then echo 'Instance is up...'; else echo 'Something is wrong with container instance'; exit 1; fi")
-                                    env.EXECUTION_ID = sh(returnStdout: true, script:"curl -s --form file=@project/3_CI_CD/4_integration_test/exec_container/test.csv --form press=OK test_score:9999/executions | jq -r '.id'").trim()
-                                    sh("echo ${env.EXECUTION_ID}")
-                                    sh(returnStdout: true, script: "if [ ! -z ${env.EXECUTION_ID} ]; then curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.csv test_score:9999/query/${env.EXECUTION_ID}; else echo 'Something is wrong with container instance'; exit 1; fi")
-                                    sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.log test_score:9999/query/${env.EXECUTION_ID}/log")
-                                    sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/system.log test_score:9999/system/log")
-                                    sh("cat project/3_CI_CD/4_integration_test/exec_container/result.csv")
-                                    sh("cat project/3_CI_CD/4_integration_test/exec_container/result.log")
-                                    sh("tail -5 project/3_CI_CD/4_integration_test/exec_container/system.log")
-                                    
-                                }
-                            }
-                        }
+                        sh("python -W ignore ContainerWrapper.py -i /pybox/model/ivnard_sample.csv -o 1582581595.089225.csv")
+                        sh(returnStdout: true, script: "if test -f '1582581595.089225.csv'; then echo 'The image scores successfully!'; else echo 'Something wrong with container. Check the logs!'; exit 1; fi")
+                        sh("cat project/3_CI_CD/4_integration_test/exec_container/1582581595.089225.csv")
                     }
+
+                    // steps {
+
+                        // script {
+
+                        //     docker.image('in92/devops_score_sidecar:v1.6').withRun('-p 9999:9999') { test ->
+                        //         docker.image('in92/devops_score_sidecar:v1.6').inside("-u 0 --entrypoint=/pybox/app/startServer.sh --link ${test.id}:test_score") {
+                        //         }
+
+                        //     docker.image('in92/devops_test_exec:v1.2').inside("--workdir=/home/test --link ${test.id}:test_score") {
+
+                        //             env.TOKEN = sh(script:"curl -s test_score:9999/", returnStdout: true).trim()
+                        //             sh(returnStdout: true, script: "if [ ${env.TOKEN} == 'pong' ]; then echo 'Instance is up...'; else echo 'Something is wrong with container instance'; exit 1; fi")
+                        //             env.EXECUTION_ID = sh(returnStdout: true, script:"curl -s --form file=@project/3_CI_CD/4_integration_test/exec_container/test.csv --form press=OK test_score:9999/executions | jq -r '.id'").trim()
+                        //             sh("echo ${env.EXECUTION_ID}")
+                        //             sh(returnStdout: true, script: "if [ ! -z ${env.EXECUTION_ID} ]; then curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.csv test_score:9999/query/${env.EXECUTION_ID}; else echo 'Something is wrong with container instance'; exit 1; fi")
+                        //             sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.log test_score:9999/query/${env.EXECUTION_ID}/log")
+                        //             sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/system.log test_score:9999/system/log")
+                        //             sh("cat project/3_CI_CD/4_integration_test/exec_container/result.csv")
+                        //             sh("cat project/3_CI_CD/4_integration_test/exec_container/result.log")
+                        //             sh("tail -5 project/3_CI_CD/4_integration_test/exec_container/system.log")
+                                    
+                        //         }
+                        //     }
+                        // }
+                    // }
 
                     post {
 
@@ -261,30 +274,30 @@ pipeline {
             }
         }
 
-        stage('SAS Model Manager Repo service') {
+        // stage('SAS Model Manager Repo service') {
 
-            agent {
-                docker {
-                    image 'in92/devops_model_registration:v2.0'
-                    args '-p 9997:9997'
-                    }
-            }
+        //     agent {
+        //         docker {
+        //             image 'in92/devops_model_registration:v2.0'
+        //             args '-p 9997:9997'
+        //             }
+        //     }
 
-            steps {
-                // sh 'python /pyservice/registration/Model_Manager_Registration_services.py'
-                sh 'python project/3_CI_CD/5_model_manager_registration_service/Model_Manager_Registration_services.py'
-            }
+        //     steps {
+        //         // sh 'python /pyservice/registration/Model_Manager_Registration_services.py'
+        //         sh 'python project/3_CI_CD/5_model_manager_registration_service/Model_Manager_Registration_services.py'
+        //     }
 
-            post {
+        //     post {
 
-            success {
-                    echo 'Model Image successfully registered!'
-                }
+        //     success {
+        //             echo 'Model Image successfully registered!'
+        //         }
 
-            failure {
-                    echo 'Model Repository fails to register the model image, please see logs.'
-                }
-            }
-        }
+        //     failure {
+        //             echo 'Model Repository fails to register the model image, please see logs.'
+        //         }
+        //     }
+        // }
     }
 }
