Testing Jenkins pipeline

diff --git a/project/3_CI_CD/Jenkinsfile b/project/3_CI_CD/Jenkinsfile
--- a/project/3_CI_CD/Jenkinsfile
+++ b/project/3_CI_CD/Jenkinsfile
@@ -17,7 +17,7 @@ pipeline {
                     }
 
                     steps{
-                        sh 'pylint --disable=C,R,W project/2_DevLab/experiment_xgboost/score.py'
+                        sh 'pylint --disable=C,R,W,E project/2_DevLab/experiment_rfor/score.py'
                     }
 
                     post {
@@ -39,7 +39,7 @@ pipeline {
                     }
 
                     steps{
-                        sh 'pylint --disable=C project/2_DevLab/experiment_xgboost/train.py'
+                        sh 'pylint --disable=C project/2_DevLab/experiment_rfor/train.py'
                     }
 
                     post {
@@ -54,237 +54,237 @@ pipeline {
             }
         }  
 
-        stage('Code Validation Test') {
+        // stage('Code Validation Test') {
 
-            parallel {
+        //     parallel {
 
-                stage('Validate Score Code') {
+        //         stage('Validate Score Code') {
 
-                    agent {
-                        docker {
-                            image 'python:3-alpine' 
-                        }
-                    }
+        //             agent {
+        //                 docker {
+        //                     image 'python:3-alpine' 
+        //                 }
+        //             }
 
-                    steps {
-                        sh 'python -m py_compile project/2_DevLab/experiment_xgboost/score.py'
-                    }
+        //             steps {
+        //                 sh 'python -m py_compile project/2_DevLab/experiment_xgboost/score.py'
+        //             }
 
-                    post {
+        //             post {
 
-                    success {
-                            echo 'Score code file successfully validated!'
-                        }
+        //             success {
+        //                     echo 'Score code file successfully validated!'
+        //                 }
 
-                    failure {
-                            echo 'Code failed the Validation test, please see logs.'
-                        }
-                    }
-                }
+        //             failure {
+        //                     echo 'Code failed the Validation test, please see logs.'
+        //                 }
+        //             }
+        //         }
 
-                stage('Validate Train Code') {
+        //         stage('Validate Train Code') {
 
-                    agent {
-                        docker {
-                            image 'python:3-alpine' 
-                        }
-                    }
+        //             agent {
+        //                 docker {
+        //                     image 'python:3-alpine' 
+        //                 }
+        //             }
 
-                    steps {
-                        sh 'python -m py_compile project/2_DevLab/experiment_xgboost/train.py'
-                    }
+        //             steps {
+        //                 sh 'python -m py_compile project/2_DevLab/experiment_xgboost/train.py'
+        //             }
 
-                    post {
+        //             post {
 
-                    success {
-                            echo 'Train code file successfully validated!'
-                        }
+        //             success {
+        //                     echo 'Train code file successfully validated!'
+        //                 }
 
-                    failure {
-                            echo 'Code failed the Validation test, please see logs.'
-                        }
-                    }
-                }
-            }
-        }
+        //             failure {
+        //                     echo 'Code failed the Validation test, please see logs.'
+        //                 }
+        //             }
+        //         }
+        //     }
+        // }
 
-        stage('Unit Test for Score code') {
+        // stage('Unit Test for Score code') {
 
-            agent {
-                docker {
-                    image 'in92/devops_pyunit:v1.1' 
-                    }
-            }
+        //     agent {
+        //         docker {
+        //             image 'in92/devops_pyunit:v1.1' 
+        //             }
+        //     }
 
-            steps {
-                sh 'python project/3_CI_CD/3_unit_test/unit_test_pipeline.py project/2_DevLab/experiment_xgboost/xgb_pipeline.pickle project/3_CI_CD/3_unit_test/test.csv result.csv'
-            }
+        //     steps {
+        //         sh 'python project/3_CI_CD/3_unit_test/unit_test_pipeline.py project/2_DevLab/experiment_xgboost/xgb_pipeline.pickle project/3_CI_CD/3_unit_test/test.csv result.csv'
+        //     }
 
-            post {
+        //     post {
 
-                success {
-                        echo 'Score code file successfully passed Unit Test!'
-                    }
+        //         success {
+        //                 echo 'Score code file successfully passed Unit Test!'
+        //             }
 
-                failure {
-                        echo 'Code failed the Unit test, please see logs.'
-                    }
-            }
+        //         failure {
+        //                 echo 'Code failed the Unit test, please see logs.'
+        //             }
+        //     }
 
-        }
+        // }
 
-        stage('Integration test for Score code') {
+        // stage('Integration test for Score code') {
 
-            // parallel{
+        //     // parallel{
 
-            //     stage("Run tests") {
+        //     //     stage("Run tests") {
 
-                    agent any
+        //             agent any
 
-                    steps {
+        //             steps {
 
-                        script {
+        //                 script {
 
-                            docker.image('in92/devops_score_sidecar:v1.6').withRun('-p 9999:9999') { test ->
-                                docker.image('in92/devops_score_sidecar:v1.6').inside("-u 0 --entrypoint=/pybox/app/startServer.sh --link ${test.id}:test_score") {
-                                }
+        //                     docker.image('in92/devops_score_sidecar:v1.6').withRun('-p 9999:9999') { test ->
+        //                         docker.image('in92/devops_score_sidecar:v1.6').inside("-u 0 --entrypoint=/pybox/app/startServer.sh --link ${test.id}:test_score") {
+        //                         }
 
-                            docker.image('in92/devops_test_exec:v1.2').inside("--workdir=/home/test --link ${test.id}:test_score") {
+        //                     docker.image('in92/devops_test_exec:v1.2').inside("--workdir=/home/test --link ${test.id}:test_score") {
 
-                                    env.TOKEN = sh(script:"curl -s test_score:9999/", returnStdout: true).trim()
-                                    sh(returnStdout: true, script: "if [ ${env.TOKEN} == 'pong' ]; then echo 'Instance is up...'; else echo 'Something is wrong with container instance'; exit 1; fi")
-                                    env.EXECUTION_ID = sh(returnStdout: true, script:"curl -s --form file=@project/3_CI_CD/4_integration_test/exec_container/test.csv --form press=OK test_score:9999/executions | jq -r '.id'").trim()
-                                    sh("echo ${env.EXECUTION_ID}")
-                                    sh(returnStdout: true, script: "if [ ! -z ${env.EXECUTION_ID} ]; then curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.csv test_score:9999/query/${env.EXECUTION_ID}; else echo 'Something is wrong with container instance'; exit 1; fi")
-                                    sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.log test_score:9999/query/${env.EXECUTION_ID}/log")
-                                    sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/system.log test_score:9999/system/log")
-                                    sh("cat project/3_CI_CD/4_integration_test/exec_container/result.csv")
-                                    sh("cat project/3_CI_CD/4_integration_test/exec_container/result.log")
-                                    sh("tail -5 project/3_CI_CD/4_integration_test/exec_container/system.log")
+        //                             env.TOKEN = sh(script:"curl -s test_score:9999/", returnStdout: true).trim()
+        //                             sh(returnStdout: true, script: "if [ ${env.TOKEN} == 'pong' ]; then echo 'Instance is up...'; else echo 'Something is wrong with container instance'; exit 1; fi")
+        //                             env.EXECUTION_ID = sh(returnStdout: true, script:"curl -s --form file=@project/3_CI_CD/4_integration_test/exec_container/test.csv --form press=OK test_score:9999/executions | jq -r '.id'").trim()
+        //                             sh("echo ${env.EXECUTION_ID}")
+        //                             sh(returnStdout: true, script: "if [ ! -z ${env.EXECUTION_ID} ]; then curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.csv test_score:9999/query/${env.EXECUTION_ID}; else echo 'Something is wrong with container instance'; exit 1; fi")
+        //                             sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/result.log test_score:9999/query/${env.EXECUTION_ID}/log")
+        //                             sh(returnStdout: true, script: "curl -s -o project/3_CI_CD/4_integration_test/exec_container/system.log test_score:9999/system/log")
+        //                             sh("cat project/3_CI_CD/4_integration_test/exec_container/result.csv")
+        //                             sh("cat project/3_CI_CD/4_integration_test/exec_container/result.log")
+        //                             sh("tail -5 project/3_CI_CD/4_integration_test/exec_container/system.log")
                                     
-                                }
-                            }
-                        }
-                    }
+        //                         }
+        //                     }
+        //                 }
+        //             }
 
-                    post {
+        //             post {
 
-                    success {
-                            echo 'Score code file successfully passed Unit Test!'
-                        }
+        //             success {
+        //                     echo 'Score code file successfully passed Unit Test!'
+        //                 }
 
-                    failure {
-                            echo 'Code failed the Unit test, please see logs.'
-                        }
-                    }
-            //     }
-            // }
-        }
+        //             failure {
+        //                     echo 'Code failed the Unit test, please see logs.'
+        //                 }
+        //             }
+        //     //     }
+        //     // }
+        // }
 
-        stage('Model MetaData Quality Test') {
+        // stage('Model MetaData Quality Test') {
 
-            parallel {
+        //     parallel {
 
-                stage('Validate inputVar.json file') {
+        //         stage('Validate inputVar.json file') {
 
-                    agent {
-                        docker {
-                            image 'python:3-alpine' 
-                        }
-                    }
+        //             agent {
+        //                 docker {
+        //                     image 'python:3-alpine' 
+        //                 }
+        //             }
 
-                    steps {
-                        sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_xgboost/inputVar.json"
-                    }
+        //             steps {
+        //                 sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_xgboost/inputVar.json"
+        //             }
 
-                    post {
+        //             post {
 
-                    success {
-                            echo 'inputVar.json file successfully validated!'
-                        }
+        //             success {
+        //                     echo 'inputVar.json file successfully validated!'
+        //                 }
 
-                    failure {
-                            echo 'inputVar.json file failed the quality test, please see review them.'
-                        }
-                    }
-                }
+        //             failure {
+        //                     echo 'inputVar.json file failed the quality test, please see review them.'
+        //                 }
+        //             }
+        //         }
 
-                stage('Validate outputVar.json file') {
+        //         stage('Validate outputVar.json file') {
 
-                    agent {
-                        docker {
-                            image 'python:3-alpine' 
-                        }
-                    }
+        //             agent {
+        //                 docker {
+        //                     image 'python:3-alpine' 
+        //                 }
+        //             }
 
-                    steps {
-                        sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_xgboost/outputVar.json"
-                    }
+        //             steps {
+        //                 sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_xgboost/outputVar.json"
+        //             }
 
-                    post {
+        //             post {
 
-                    success {
-                            echo 'outputVar.json file successfully validated!'
-                        }
+        //             success {
+        //                     echo 'outputVar.json file successfully validated!'
+        //                 }
 
-                    failure {
-                            echo 'outputVar.json file failed the quality test, please see review them.'
-                        }
-                    }
+        //             failure {
+        //                     echo 'outputVar.json file failed the quality test, please see review them.'
+        //                 }
+        //             }
 
-                }
+        //         }
 
-                stage('Validate fileMetadata.json file') {
+        //         stage('Validate fileMetadata.json file') {
 
-                    agent {
-                        docker {
-                            image 'python:3-alpine' 
-                        }
-                    }
+        //             agent {
+        //                 docker {
+        //                     image 'python:3-alpine' 
+        //                 }
+        //             }
 
-                    steps {
-                        sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_xgboost/fileMetadata.json"
-                    }
+        //             steps {
+        //                 sh "python -c 'import sys,json; json.load(sys.stdin)' < project/2_DevLab/experiment_xgboost/fileMetadata.json"
+        //             }
 
-                    post {
+        //             post {
 
-                    success {
-                            echo 'fileMetadata.json file successfully validated!'
-                        }
+        //             success {
+        //                     echo 'fileMetadata.json file successfully validated!'
+        //                 }
 
-                    failure {
-                            echo 'fileMetadata.json file failed the quality test, please see review them.'
-                        }
-                    }
+        //             failure {
+        //                     echo 'fileMetadata.json file failed the quality test, please see review them.'
+        //                 }
+        //             }
 
-                }
-            }
-        }
+        //         }
+        //     }
+        // }
 
-        stage('SAS Model Manager Repo service') {
+        // stage('SAS Model Manager Repo service') {
 
-            agent {
-                docker {
-                    image 'in92/devops_model_registration:v2.0'
-                    args '-p 9997:9997'
-                    }
-            }
+        //     agent {
+        //         docker {
+        //             image 'in92/devops_model_registration:v2.0'
+        //             args '-p 9997:9997'
+        //             }
+        //     }
 
-            steps {
-                // sh 'python /pyservice/registration/Model_Manager_Registration_services.py'
-                sh 'python project/3_CI_CD/5_model_manager_registration_service/Model_Manager_Registration_services.py'
-            }
+        //     steps {
+        //         // sh 'python /pyservice/registration/Model_Manager_Registration_services.py'
+        //         sh 'python project/3_CI_CD/5_model_manager_registration_service/Model_Manager_Registration_services.py'
+        //     }
 
-            post {
+        //     post {
 
-            success {
-                    echo 'Model Image successfully registered!'
-                }
+        //     success {
+        //             echo 'Model Image successfully registered!'
+        //         }
 
-            failure {
-                    echo 'Model Repository fails to register the model image, please see logs.'
-                }
-            }
-        }
+        //     failure {
+        //             echo 'Model Repository fails to register the model image, please see logs.'
+        //         }
+        //     }
+        // }
     }
 }
